// <auto-generated />
namespace Building.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first_update_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_update_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201608030654360_first_update_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
